### PR TITLE
Rename project to `tmate-replica`

### PR DESCRIPTION
**Pull request by graysonwright**
Rename project to `tmate-server`

Hey, I just discovered this project,
and I'm super excited about being able to pair with my brother
who lives across the country.
Thanks for all your work!

I was scrolling down your homepage to try and figure out how it worked,
and I saw this github repository listed.
The name `tmate-slave` jumped out at me,
and though I love the project,
I was a bit turned off by the name.
Many software projects are moving away
from the `master/slave` naming convention,
in an attempt to present a more inclusive environment.

A couple years ago Drupal changed their terminology
away from `master/slave`,
and [this comment from the issue discussion][drupal-comment]
captured their reasoning beautifully.

[drupal-comment]: https://www.drupal.org/node/2275877#comment-8831441

Drupal's, and Django's, and other projects' renamings
were met with many grateful responses,
and it is becoming the norm to use `primary / replica`,
or in this case something like `client / sever`,
to describe the relationship.

I did my best to replace the instances of `slave` with `server`,
and it looks like everything still works correctly.
Let me know if it looks good to you.

Again, I really enjoy your project and I can't wait
to start using it regularly.
Thanks for your contributions,
and for helping make open source more accessible to all!

### CODE REVIEW

**Comment by nviennot** [comment]
Hi @graysonwright :)

Thank you for the pull request :)
Sorry to not reply sooner, I dropped off my radar.

I had started to write a paper: http://viennot.biz/tmate.pdf and the terminology I picked was "tmate-replica". The word server is already used by tmux client/server architecture, we needed something else.

So what do you think about tmate-replica?

Also, please make a symlink `tmate-slave -> tmate-replica` so that old install scripts continue to work even if they are not aware of the new name

Thank you :))
Nico

**Comment by graysonwright** [comment]
@nviennot sorry for waiting a year before getting back to this.

I just updated my commit to use the `replica` naming scheme. I'm not familiar with the install scripts, so I don't know where the symlink should go. Is that something that you can take care of? I wouldn't want to mess it up.

Let me know what you think!

Thanks again. (=

**Comment by nviennot** [comment]
I'll take care of this once I upgrade the infrastructure, which is not for now.

**Comment by anarcat** [comment]
the project was renamed to tmate-ssh-server in #41 so i believe this can be closed.

**Comment by cryptomilk** [comment]
Closing as the new name is tmate-ssh-server.

**Pull request closed without merging**
