### PR TITLE
Add RPM SPEC and supporting files

### PR DESCRIPTION
**Pull request by skpy**
This adds a `SPEC` directory in which is a `tmate-slave.spec` file that can be used to build an RPM on RHEL 7 (and derivative) systems. It also provides a number of ancillary files in the `RPM` directory to support proper daemonization of `tmate-slave`.

README.md updated accordingly.

To facilitate people attempting to build RPMs, a binary release of `tmate-slave` would be very helpful.  As it is, I had to manually export the source from the git repo, then build a `tmate-slave-1.8.tar.gz` file for use with the `rpmbuild` command.

The 1.8 release at [nviennot/tmate-slave/releases](https://github.com/nviennot/tmate-slave/releases) is, in fact, the upstream tmux source.

### CODE REVIEW

**Comment by nviennot** [comment]
Hi Scott,

For some reason I never saw this pull request.
My apologies. This looks quite good.

Since then, I changed a couple of things in tmate-slave:
1) no more log file to specify. The log goes either to stderr, or syslog, so the log rotate might not be useful anymore.
2) ssh-keygen might need a -E md5 for the fingerprint.

Sorry again for the long delay...

Have a good one,
Nico.

**Comment by skpy** [comment]
@nviennot updated.  I'm not a systemd expert yet, so the pre- and post- RPM scripts may have some rough edges.  This SPEC has been working for our needs, though.

One note is that since this SPEC isn't tied to a current release, I updated the `version` to be the date at which I had updated this file internally.

**Comment by skpy** [comment]
Additionally, building this RPM for RHEL7 requires `msgpack-devel`, available from [COPR](https://copr-be.cloud.fedoraproject.org/results/ngompa/msgpack/). Installing this RPM requires `msgpack` version 1.3.0, also available from COPR.

**Comment by skpy** [comment]
@nviennot I've updated the SPEC for the latest iteration of the code.  Care to take another look?

**Comment by nviennot** [comment]
I'll have to come back to you on this one, sorry for the late reply

**Comment by nviennot** [comment]
Can we use a repository just for the RPM stuff instead? I've created it here: https://github.com/tmate-io/tmate-rpm

**Comment by cryptomilk** [comment]
I would suggest to create a package for fedora and epel. Spec files should be maintained in the Fedora source code repository.

**Comment by nviennot** [comment]
Hello @skpy,

I'm sorry I never got to merge your work. I'm not sure what's the status of this PR, and if it is still relevant. What's the status?

**Comment by skpy** [comment]
Hi.  I've lost track of this PR.  We've since moved to invoking tmate through a container, so we don't really use the RPM build process any more.  I'll close this.  If someone else wants to pick it up, they can!

**Pull request closed without merging**
